pslot: "mlb.02"
start_pdy: '20210701'
end_pdy: '20210701'
cycs: ["06"]
run: "gdas"
homegdas: "/work2/noaa/da/gvernier/sandboxes/gdas-marine-viz/"
base_exp_path: "/work2/noaa/da/gvernier/runs/mlb/{{ pslot }}/COMROOT/{{ pslot }}"
vrfyout: "/work2/noaa/da/gvernier/sandboxes/gdas-marine-viz/test/{{ pslot }}"
plot_ensemble_b: "OFF"
plot_parametric_b: "OFF"
plot_background: "OFF"
plot_increment: "ON"
plot_analysis: "OFF"
eva_plots: "ON"
qos: "batch"
hpc: "hercules"
eva_module: "EVA/orion"
