#!/usr/bin/env python3
"""
Generate an HTML index file to organize timeseries figures from marine observation statistics.

This script creates an interactive HTML index that organizes timeseries plots by platform type,
ocean basin, and experiment. It supports both individual timeseries plots and multi        .gallery {
            display        .image-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 25px;
            margin-top: 20px;
        };
            background: white;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            width: 100%;
        }ment
comparison plots generated by plot_timeseries.py.

Usage:
    python generate_timeseries_index.py /path/to/figures/directory
    python generate_timeseries_index.py /path/to/figures/directory --config config.yaml
    python generate_timeseries_index.py /path/to/figures/directory --title "Custom Title"
"""

import os
import sys
import argparse
import yaml
from collections import defaultdict
import re


def parse_timeseries_filename(filename):
    """
    Parse a timeseries PNG filename to extract platform, variable, basin, and plot type.

    Expected formats:
    - Platform_Name_-_Basin_Name_timeseries.png (individual experiment)
    - Platform_Name_-_Basin_Name_comparison.png (multi-experiment comparison)
    - Experiment_Name_-_Platform_Name_-_Basin_Name_timeseries.png (individual experiment with experiment prefix)

    Examples:
    - Surface_Drifters_Temp_-_Global_comparison.png
    - Argo_Profiles_Salt_0-10m_-_Atlantic_comparison.png
    - SST_VIIRS_N20_-_Pacific_comparison.png
    - cp402d_-_AMSR2_Ice_Concentration_North_-_Global_timeseries.png

    Returns:
        tuple: (platform, variable, basin, plot_type, depth_info)
    """
    # Remove .png extension
    basename = filename.replace('.png', '')

    # Determine plot type
    if basename.endswith('_timeseries'):
        plot_type = 'timeseries'
        basename = basename.replace('_timeseries', '')
    elif basename.endswith('_comparison'):
        plot_type = 'comparison'
        basename = basename.replace('_comparison', '')
    else:
        return None, None, None, None, None

    # Find the separator "_-_" to split parts
    separator = '_-_'
    if separator not in basename:
        return None, None, None, None, None

    parts = basename.split(separator)

    # Handle different formats:
    # Format 1: Platform_-_Basin (2 parts)
    # Format 2: Experiment_-_Platform_-_Basin (3 parts)
    if len(parts) == 2:
        platform_part = parts[0]
        basin_part = parts[1]
    elif len(parts) == 3:
        # Skip the experiment name (first part) and use platform and basin
        platform_part = parts[1]
        basin_part = parts[2]
    else:
        return None, None, None, None, None

    # Extract variable and depth information from platform name
    variable = None
    depth_info = None

    # Check for depth information in platform name (e.g., "0-10m", "300-2000m")
    depth_pattern = r'_(\d+[-‐]\d+m)$'  # Match depth at end like "_0-10m"
    depth_match = re.search(depth_pattern, platform_part)
    if depth_match:
        depth_info = depth_match.group(1)
        platform_part = platform_part.replace('_' + depth_info, '')

    # Check for variable type indicators
    if platform_part.endswith('_Temp'):
        variable = 'Temperature'
        platform_part = platform_part.replace('_Temp', '')
    elif platform_part.endswith('_Salt'):
        variable = 'Salinity'
        platform_part = platform_part.replace('_Salt', '')
    elif platform_part.startswith('SST_'):
        variable = 'SST'
    elif platform_part.startswith('ADT_'):
        variable = 'ADT'
    elif (platform_part.startswith('AMSR2_') or
          'ICEC' in platform_part.upper() or
          'Ice_Concentration' in platform_part or
          platform_part.lower().startswith('amsr2')):
        variable = 'ICEC'
    else:
        variable = 'Temperature'  # Default assumption

    # Convert underscores to spaces for display
    platform_display = platform_part.replace('_', ' ')
    basin_display = basin_part.replace('_', ' ')

    return platform_display.strip(), variable, basin_display.strip(), plot_type, depth_info


def organize_timeseries_files(directory):
    """
    Organize PNG files by platform type, variable, and basin.

    Returns:
        dict: Organized structure with platforms, variables, basins, and plot types
    """
    files_data = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(str))))

    # Get all PNG files in directory
    png_files = [f for f in os.listdir(directory) if f.endswith('.png')]

    for filename in png_files:
        platform, variable, basin, plot_type, depth_info = parse_timeseries_filename(filename)

        if platform and variable and basin and plot_type:
            # Create a platform key that includes depth info if present
            platform_key = platform
            if depth_info:
                platform_key = f"{platform} ({depth_info})"

            files_data[platform_key][variable][basin][plot_type] = filename

    return files_data


def load_config_experiments(config_file):
    """Load experiment names from configuration file."""
    if not config_file or not os.path.exists(config_file):
        return []

    try:
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)

        if 'experiments' in config and isinstance(config['experiments'], dict):
            return list(config['experiments'].keys())
        else:
            return []
    except Exception as e:
        print(f"Warning: Failed to load config file {config_file}: {e}")
        return []


def get_unique_platforms(files_data):
    """Get sorted list of unique platform types."""
    platforms = list(files_data.keys())

    # Custom sorting to group related platforms together
    def sort_key(platform):
        # Put surface drifters first
        if 'Drifter' in platform:
            return (0, platform)
        # Group Argo by variable and depth
        elif 'Argo' in platform:
            if 'Temp' in platform or 'Temperature' in platform:
                return (1, platform)
            elif 'Salt' in platform or 'Salinity' in platform:
                return (2, platform)
            else:
                return (1, platform)
        # Put SST platforms next
        elif 'SST' in platform:
            return (3, platform)
        # Put ICEC/AMSR2 platforms after SST
        elif ('AMSR2' in platform or 'ICEC' in platform.upper() or
              'Ice Concentration' in platform or 'amsr2' in platform.lower()):
            return (4, platform)
        else:
            return (5, platform)

    return sorted(platforms, key=sort_key)


def get_unique_variables(files_data):
    """Get sorted list of unique variables."""
    variables = set()
    for platform_data in files_data.values():
        variables.update(platform_data.keys())

    # Preferred order for variables
    variable_order = ['Temperature', 'Salinity', 'ADT', 'SST', 'ICEC']
    return [var for var in variable_order if var in variables]


def get_unique_basins(files_data):
    """Get sorted list of unique ocean basins."""
    basins = set()
    for platform_data in files_data.values():
        for variable_data in platform_data.values():
            basins.update(variable_data.keys())

    # Preferred order for ocean basins
    basin_order = ['Global', 'Arctic', 'Atlantic', 'Indian', 'Pacific', 'Southern']
    return [basin for basin in basin_order if basin in basins]


def generate_timeseries_html(files_data, title=None, experiments=None, output_file='timeseries_index.html'):
    """
    Generate HTML index file for the organized timeseries figures.
    """
    platforms = get_unique_platforms(files_data)
    variables = get_unique_variables(files_data)
    basins = get_unique_basins(files_data)

    if not platforms:
        print("No valid timeseries PNG files found to organize.")
        return

    # Set default title if not provided
    if not title:
        title = "Marine Observation Statistics - Time Series Analysis"

    # Set default experiments if not provided
    if not experiments:
        experiments = []

    experiments_text = f"Experiments: {', '.join(experiments)}" if experiments else "Marine Observation Time Series"

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
        }}
        .header {{
            text-align: center;
            margin-bottom: 30px;
            padding: 20px;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }}
        .header h1 {{
            color: #2c3e50;
            font-size: 2.2em;
            margin-bottom: 10px;
            border-bottom: 3px solid #3498db;
            display: inline-block;
            padding-bottom: 10px;
        }}
        .header p {{
            font-size: 1.1em;
            color: #34495e;
            margin: 10px 0;
        }}
        .controls {{
            background: white;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            margin-bottom: 25px;
        }}
        .control-group {{
            margin-bottom: 20px;
        }}
        .control-label {{
            display: block;
            font-weight: 600;
            margin-bottom: 10px;
            color: #2c3e50;
            font-size: 1.1em;
        }}
        .button-group {{
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
        }}
        .button {{
            padding: 10px 18px;
            cursor: pointer;
            background: linear-gradient(135deg, #3498db, #2980b9);
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 0.9em;
            font-weight: 500;
            transition: all 0.3s ease;
            box-shadow: 0 2px 8px rgba(52, 152, 219, 0.3);
        }}
        .button:hover {{
            background: linear-gradient(135deg, #2980b9, #1f5f8b);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(52, 152, 219, 0.4);
        }}
        .button.active {{
            background: linear-gradient(135deg, #e74c3c, #c0392b);
            box-shadow: 0 4px 12px rgba(231, 76, 60, 0.4);
        }}
        select {{
            padding: 12px 16px;
            font-size: 1em;
            border-radius: 8px;
            border: 2px solid #ddd;
            background: white;
            cursor: pointer;
            min-width: 250px;
            transition: border-color 0.3s ease;
        }}
        select:focus {{
            border-color: #3498db;
            outline: none;
        }}
        .gallery {{
            display: none;
            background: white;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            width: 100%;
        }}

        .image-container {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 25px;
            margin-top: 20px;
        }}
        .image-wrapper {{
            background: #f8f9fa;
            border-radius: 10px;
            padding: 15px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            transition: transform 0.3s ease;
        }}
        .image-wrapper:hover {{
            transform: translateY(-5px);
        }}
        .image-wrapper img {{
            width: 100%;
            height: auto;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        .image-title {{
            margin-top: 12px;
            font-weight: 600;
            color: #2c3e50;
            text-align: center;
            font-size: 1.05em;
        }}
        .no-data {{
            text-align: center;
            color: #7f8c8d;
            font-style: italic;
            padding: 50px;
            font-size: 1.2em;
        }}
        .stats-summary {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            font-size: 0.9em;
            color: #2c3e50;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>{experiments_text}</p>
        <div class="stats-summary">
            Found {len(platforms)} platforms • {len(variables)} variables • {len(basins)} ocean basins
        </div>
    </div>

    <!-- Main container with side-by-side layout -->
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <!-- Left panel for controls -->
        <div class="controls" style="flex: 0 0 400px; min-width: 400px;">
            <div class="control-group">
                <label class="control-label">🛰️ Select Platform:</label>
                <select id="platformSelect" onchange="onPlatformChange(this.value)">
                    <option value="">Choose observation platform...</option>"""

    # Add platform options
    for platform in platforms:
        html_content += f"""
                <option value="{platform}">{platform}</option>"""

    html_content += """
                </select>
            </div>

            <div class="control-group">
                <label class="control-label">📊 Select Variable:</label>
                <select id="variableSelect" onchange="onVariableChange(this.value)" disabled>
                    <option value="">Choose variable...</option>
                </select>
            </div>

            <div class="control-group">
                <label class="control-label">🌊 Ocean Basin:</label>
                <div class="button-group">"""

    # Add basin buttons
    for basin in basins:
        html_content += f"""
                    <button class="button" id="basin_{basin}" onclick="showTimeseries('{basin}')" disabled>{basin}</button>"""

    html_content += """
                </div>
            </div>
        </div>

        <!-- Right panel for images -->
        <div style="flex: 1; min-width: 0;">
            <div class="gallery" id="gallery">
                <div id="imageContainer"></div>
            </div>
        </div>
    </div>

    <script>
        // Global variables
        var currentPlatform = '';
        var currentVariable = '';
        var currentBasin = '';
        var currentPlotType = 'comparison';

        // File data structure"""

    # Add JavaScript data structure
    html_content += "\n        var filesData = {\n"

    for platform in platforms:
        html_content += f"            '{platform}': {{\n"
        for variable in variables:
            if variable in files_data[platform]:
                html_content += f"                '{variable}': {{\n"
                for basin in basins:
                    if basin in files_data[platform][variable]:
                        html_content += f"                    '{basin}': {{\n"
                        for plot_type, filename in files_data[platform][variable][basin].items():
                            html_content += f"                        '{plot_type}': '{filename}',\n"
                        html_content += "                    },\n"
                html_content += "                },\n"
        html_content += "            },\n"

    html_content += "        };\n"

    # Add the rest of the JavaScript
    html_content += """

        function onPlatformChange(platform) {
            currentPlatform = platform;

            var variableSelect = document.getElementById('variableSelect');
            var basinButtons = document.querySelectorAll('.button[id^="basin_"]');

            // Reset and disable controls
            variableSelect.innerHTML = '<option value="">Choose variable...</option>';
            variableSelect.disabled = !platform;
            currentVariable = '';
            currentBasin = '';

            basinButtons.forEach(function(button) {
                button.disabled = true;
                button.classList.remove('active');
            });

            document.getElementById('gallery').style.display = 'none';

            if (platform && filesData[platform]) {
                // Populate variables for this platform
                Object.keys(filesData[platform]).forEach(function(variable) {
                    var option = document.createElement('option');
                    option.value = variable;
                    option.textContent = variable;
                    variableSelect.appendChild(option);
                });
                variableSelect.disabled = false;
            }
        }

        function onVariableChange(variable) {
            currentVariable = variable;

            var basinButtons = document.querySelectorAll('.button[id^="basin_"]');

            // Reset basin selection
            currentBasin = '';
            basinButtons.forEach(function(button) {
                button.classList.remove('active');
                button.disabled = true;
            });

            document.getElementById('gallery').style.display = 'none';

            if (currentPlatform && variable && filesData[currentPlatform] && filesData[currentPlatform][variable]) {
                // Enable basin buttons that have data
                Object.keys(filesData[currentPlatform][variable]).forEach(function(basin) {
                    var button = document.getElementById('basin_' + basin);
                    if (button) {
                        button.disabled = false;
                    }
                });
            }
        }

        function showTimeseries(basin) {
            if (!currentPlatform || !currentVariable) {
                alert('Please select a platform and variable first.');
                return;
            }

            currentBasin = basin;
            updateActiveBasinButton(basin);
            displayImages();
        }



        function displayImages() {
            var container = document.getElementById('imageContainer');
            var basePath = window.location.pathname.substring(0, window.location.pathname.lastIndexOf('/') + 1);

            // Check if data exists for this combination
            if (!filesData[currentPlatform] ||
                !filesData[currentPlatform][currentVariable] ||
                !filesData[currentPlatform][currentVariable][currentBasin]) {
                container.innerHTML = '<div class="no-data">No data available for ' +
                    currentPlatform + ' (' + currentVariable + ') in ' + currentBasin + ' ocean.</div>';
                document.getElementById('gallery').style.display = 'block';
                return;
            }

            var basinData = filesData[currentPlatform][currentVariable][currentBasin];
            var filename = basinData[currentPlotType];

            if (!filename) {
                container.innerHTML = '<div class="no-data">No multi-experiment comparison plot available for ' +
                    currentPlatform + ' (' + currentVariable + ') in ' + currentBasin + ' ocean.</div>';
            } else {
                var imageTitle = currentPlatform + ' - ' + currentVariable + ' - ' + currentBasin + ' Ocean';

                var imageHTML = '<div class="image-container">';
                imageHTML += '<div class="image-wrapper">';
                imageHTML += '<img src="' + basePath + filename + '" alt="' + imageTitle + '" title="' + imageTitle + '">';
                imageHTML += '<div class="image-title">Multi-Experiment Comparison<br>' + imageTitle + '</div>';
                imageHTML += '</div>';
                imageHTML += '</div>';

                container.innerHTML = imageHTML;
            }

            document.getElementById('gallery').style.display = 'block';
        }

        function updateActiveBasinButton(selectedBasin) {
            var buttons = document.querySelectorAll('.button[id^="basin_"]');
            buttons.forEach(function(button) {
                if (button.id === 'basin_' + selectedBasin) {
                    button.classList.add('active');
                } else {
                    button.classList.remove('active');
                }
            });
        }


    </script>
</body>
</html>"""

    return html_content


def main():
    parser = argparse.ArgumentParser(
        description='Generate HTML index for marine observation timeseries figures',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate_timeseries_index.py /path/to/figures
  python generate_timeseries_index.py /path/to/figures --config config.yaml
  python generate_timeseries_index.py /path/to/figures --title "My Custom Analysis"
  python generate_timeseries_index.py ./real-time --experiments "CP4.02d,CP4.03"
        """
    )

    parser.add_argument('directory', help='Directory containing timeseries PNG files')
    parser.add_argument('--config', default=None,
                        help='Configuration YAML file to extract experiment names')
    parser.add_argument('--title', default=None,
                        help='Title for the HTML page (default: auto-generated)')
    parser.add_argument('--experiments', default=None,
                        help='Comma-separated list of experiment names')
    parser.add_argument('--output', default='timeseries_index.html',
                        help='Output HTML filename (default: timeseries_index.html)')

    args = parser.parse_args()

    # Validate directory
    if not os.path.isdir(args.directory):
        print(f"Error: Directory '{args.directory}' does not exist.")
        sys.exit(1)

    # Count PNG files
    png_files = [f for f in os.listdir(args.directory) if f.endswith('.png')]
    if not png_files:
        print(f"Error: No PNG files found in '{args.directory}'.")
        sys.exit(1)

    print(f"Found {len(png_files)} PNG files in '{args.directory}'")

    # Organize files
    print("Analyzing timeseries file structure...")
    files_data = organize_timeseries_files(args.directory)

    if not files_data:
        print("Error: No valid timeseries files found.")
        print("Expected filename formats:")
        print("  - Platform_Name_-_Basin_Name_timeseries.png")
        print("  - Platform_Name_-_Basin_Name_comparison.png")
        sys.exit(1)

    # Get experiment names
    experiments = []
    if args.experiments:
        experiments = [exp.strip() for exp in args.experiments.split(',')]
    elif args.config:
        experiments = load_config_experiments(args.config)

    # Print summary
    platforms = get_unique_platforms(files_data)
    variables = get_unique_variables(files_data)
    basins = get_unique_basins(files_data)

    print(f"Found {len(platforms)} platform types: {', '.join(platforms[:3])}{'...' if len(platforms) > 3 else ''}")
    print(f"Found {len(variables)} variables: {', '.join(variables)}")
    print(f"Found {len(basins)} ocean basins: {', '.join(basins)}")

    if experiments:
        print(f"Experiments: {', '.join(experiments)}")

    # Generate HTML
    print("Generating HTML index...")
    html_content = generate_timeseries_html(files_data, args.title, experiments, args.output)

    # Write output file
    output_path = os.path.join(args.directory, args.output)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"HTML index generated: {output_path}")
    print(f"Open in browser: file://{os.path.abspath(output_path)}")


if __name__ == '__main__':
    main()
